config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'posts/index'
  
  get 'posts/search'

  resources :posts do
    member do
        post 'upvote'
        post 'downvote'
    end
    resources :comments
  end

  resources :comments do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :parent, polymorphic: true
  has_many :comments, as: :parent

  validates :text, presence: true

  def get_parent_post
  	comment = self
  	while comment.parent_type == 'Comment'
  		comment = Comment.find(comment.parent_id)
  	end
  	Post.find(comment.parent_id)
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, as: :parent
	
	validates :title, presence: true

	def Post.search(criteria)
		comments_search = Comment.where("text like ?", "%#{criteria}%")
		post_id_list = []
		comments_search.each { |comment| post_id_list << comment.get_parent_post.id }
		Post.where("title like ? or id in ( ? )", "%#{criteria}%", post_id_list).order('vote desc')
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def new
		if params[:post_id]
			@parent = Post.find(params[:post_id])
		elsif
			@parent = Comment.find(params[:comment_id])
		end
		@comment = @parent.comments.build
	end

	def create
		if params[:post_id]
			@parent = Post.find(params[:post_id])
			post = @parent
		elsif
			@parent = Comment.find(params[:comment_id])
			post = @parent.get_parent_post
		end
		@comment = @parent.comments.create comment_params
		if @comment.valid?
			redirect_to post_path(post)
		else
			render 'new'
		end
	end

	private

	def comment_params
		params.require(:comment).permit(:author, :text)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	helper_method :sort_column, :sort_direction

	def index
		@posts = Post.order(sort_column + ' ' + sort_direction)
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.vote = 0
		if @post.save
			flash[:success] = "Your post has been created."
			redirect_to posts_path
		else
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		@post.update post_params
		if @post.valid?
			flash[:success] = "Your post has been updated."
			redirect_to posts_path
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		flash[:success] = "Your post has been deleted."
		redirect_to posts_path
	end

	def upvote
		@post = Post.find(params[:id])
		@post.vote += 1
		respond_to do |format|
			if @post.save
				format.html{redirect_to posts_path}
				format.json{render json: @post }
			else
				format.html{render :index}
				format.json{render json: @post.errors, status: :unprocessable_entity}
			end
		end
	end

	def downvote
		@post = Post.find(params[:id])
		@post.vote -= 1
		respond_to do |format|
			if @post.save
				format.html{redirect_to posts_path}
				format.json{render json: @post }
			else
				format.html{render :index}
				format.json{render json: @post.errors, status: :unprocessable_entity}
			end
		end
	end

	def search
		if(params[:search] != nil)
			@posts = Post.search(params[:search])
		else
			#HELP if I sort a column on a search result, the search are no longer correct
			@posts = Post.order(sort_column + ' ' + sort_direction)
		end
		render 'index'
	end

	private

	def post_params
		params.require(:post).permit(:title, :link)
	end

	def sort_column  
		Post.column_names.include?(params[:sort]) ? params[:sort] : "vote"
	end  

	def sort_direction  
		%w[asc desc].include?(params[:direction]) ?  params[:direction] : "desc" 
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper

	def sortable(column, title = nil)  
		title ||= column.titleize  
		direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"  
		link_to title, :sort => column, :direction => direction  
	end  
	
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<% comment.comments.each do |subcomment| %>
	<blockquote>
		<p><%=subcomment.author%> at <%=subcomment.created_at.strftime("%b %e, %Y")%></p>
		<footer><%=subcomment.text%> <%= link_to 'Add a comment', new_comment_comment_path(subcomment), class: "btn-sm btn-primary"%></footer></footer>
	  
	  <%= render :partial => 'comments/comment', :object => subcomment %>
	</blockquote>
<% end %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<% if @comment.errors.any? %>
<div id="error_explanation" class="alert alert-danger">
  <% @comment.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
</div>
<% end %>


<%= form_for [@parent, @comment], html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label :author, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :author, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :text, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :text, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary"%>
      <%= link_to 'Back', post_path(@comment.get_parent_post), class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          </button>
          <a class="navbar-brand" href="/">Reddit App</a>
        </div>

        <div class="collapse navbar-collapse">
        	<ul class="nav navbar-nav">
	            <li class="active"><%= link_to 'All posts', posts_path %></li>
	            <li><%= link_to 'New post', new_post_path %></li>
        	</ul>
        	<!-- Search form -->
       		<%= form_tag posts_search_path, class: "navbar-form navbar-right", method: :GET do %>
    				<div class="form-group">
              <%= text_field_tag :search, nil, class: "form-control" %>
            </div>
    				<%= submit_tag "Search", class: "btn btn-primary"%>
    			<% end %>
			<!-- end Search form -->

        </div><!--/.nav-collapse -->

      </div>
    </div>

    <div class="container">

      <div class="starter-template">
      	<br /><br /><br />

		<% flash.each do |name, msg| %>
	        <%= content_tag :div, msg, class: "alert alert-#{name}"%>
	    <% end %>

		<%= yield %>

      </div>

    </div><!-- /.container -->

</body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
<div id="error_explanation" class="alert alert-danger">
  <% @post.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
</div>
<% end %>

<%= form_for @post, html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :link, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :link, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary"%>
      <%= link_to 'Back', posts_path, class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>All posts</h1>

<table class="table table-striped">
	<tr>

		<th><%= sortable "title", "Post" %></th>
		<th><%= sortable "created_at", "Date" %></th>
		<th>Actions</th>
		<th colspan="2"><%= sortable "vote", "Upvotes" %></th>
	</tr>
<% @posts.each do |post|%>
	<tr>
		<td><a href="<%= post.link %>"><%= post.title %></a></td>
		<td><%= post.created_at.strftime("%b %e, %Y") %></td>
		<td>
			<div class="btn-group">
				<%= link_to 'Show', post_path(post), class: "btn btn-primary" %>
				<%= link_to 'Edit', edit_post_path(post) , class: "btn btn-primary" %>
				<%= link_to 'Delete', post_path(post),
	                    method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-primary"%>
	        </div>
	    </td>
	    <td id="vote_<%=post.id%>"><%=pluralize(post.vote, "vote")%></td>
	    <td>
	    	<div class="btn-group">
	    		<button class="btn btn-default glyphicon glyphicon-thumbs-up" id="<%=post.id%>/upvote"></button>
	    		<button class="btn btn-default glyphicon glyphicon-thumbs-down" id="<%=post.id%>/downvote"></button>
			</div>
		</td>	
	</tr>
<% end %>
</table>
<br />
<%= link_to 'New post', new_post_path , class: "btn btn-primary"%><br />


<script type="text/javascript">
$('.glyphicon').click(function(e){

	var request = $.ajax({
		url: "/posts/" + e.target.id,
		type: "POST",
		data: {},
		dataType: "json"
	});

	request.done(function(data){
		$('#vote_'+data.id)[0].textContent = data.vote+" votes"
	})

	request.fail(function(data){
		$('.message').append("<p> There was an error upvoting/downvoting the post.</p>")
	})

});
</script>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1>Show post</h1>

<h3>
  <a href="<%= @post.link %>"><%= @post.title %></a>
</h3>
<p>
  <%=pluralize(@post.vote, "vote")%>
</p>
<%= link_to 'Add a comment', new_post_comment_path(@post), class: "btn btn-primary"%>
<%= link_to 'Back', posts_path, class: "btn btn-primary" %>
<br /><br />
<div class="well">
	<h3>Comments</h3>
	<%= render :partial => 'comments/comment', :object => @post %>
</div>
<%= link_to 'Add a comment', new_post_comment_path(@post), class: "btn btn-primary"%>
<%= link_to 'Back', posts_path, class: "btn btn-primary" %>